name: 'meeting-1on1-action'
description: 'Manage 1:1 meeting issues'

branding:
  icon: 'users'
  color: 'green'

inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  configuration-path:
    description: 'The path for the issue configurations'
    default: '.github/101.yml'
    required: true
  scheduled-day:
    description: 'Is the meeting today or tomorrow?'
    default: 'today'
    required: false

outputs:
  url:
    description: '1:1 issue URL'

runs:
  using: 'node12'
  main: 'dist/index.js'
